wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1735360614
    t:
      1:
      - 1
      - 50
      - 55
      3:
      - 13
      - 14
      - 35
      4: 3.7.12
      5: 0.12.21
      8:
      - 6
capture_video:
  desc: null
  value: false
capture_video_freq:
  desc: null
  value: 1464
capture_video_len:
  desc: null
  value: 100
checkpoint:
  desc: null
  value: ''
experiment:
  desc: null
  value: ''
force_render:
  desc: null
  value: true
graphics_device_id:
  desc: null
  value: 0
headless:
  desc: null
  value: false
max_iterations:
  desc: null
  value: ''
multi_gpu:
  desc: null
  value: false
num_envs:
  desc: null
  value: ''
num_subscenes:
  desc: null
  value: 4
num_threads:
  desc: null
  value: 4
pbt:
  desc: null
  value:
    enabled: false
physics_engine:
  desc: null
  value: physx
pipeline:
  desc: null
  value: gpu
rl_device:
  desc: null
  value: cuda:0
seed:
  desc: null
  value: 42
sigma:
  desc: null
  value: ''
sim_device:
  desc: null
  value: cuda:0
solver_type:
  desc: null
  value: 1
task:
  desc: null
  value:
    env:
      aggregate_mode: true
      apply_safety_damping: true
      asymmetric_obs: true
      clipActions: 1.0
      clipObservations: 5.0
      command_mode: torque
      control_decimation: 1
      cube_obs_keypoints: true
      enableCameraSensors: false
      enable_ft_sensors: false
      envSpacing: 1.0
      episodeLength: 750
      normalize_action: true
      normalize_obs: true
      numEnvs: 16384
      reset_distribution:
        object_initial_state:
          type: random
        robot_initial_state:
          dof_pos_stddev: 0.4
          dof_vel_stddev: 0.2
          type: default
      reward_terms:
        finger_move_penalty:
          activate: true
          weight: -0.5
        finger_reach_object_rate:
          activate: true
          norm_p: 2
          weight: -250
        keypoints_dist:
          activate: true
          weight: 2000
        object_dist:
          activate: false
          weight: 2000
        object_rot:
          activate: false
          weight: 2000
      task_difficulty: 4
      termination_conditions:
        success:
          orientation_tolerance: 0.4
          position_tolerance: 0.02
    name: Trifinger
    physics_engine: physx
    sim:
      dt: 0.02
      gravity:
      - 0.0
      - 0.0
      - -9.81
      physx:
        bounce_threshold_velocity: 0.5
        contact_collection: 0
        contact_offset: 0.002
        default_buffer_size_multiplier: 5.0
        max_depenetration_velocity: 1000.0
        max_gpu_contact_pairs: 8388608
        num_position_iterations: 8
        num_subscenes: 4
        num_threads: 4
        num_velocity_iterations: 0
        rest_offset: 0.0
        solver_type: 1
        use_gpu: true
      substeps: 4
      up_axis: z
      use_gpu_pipeline: true
    task:
      randomization_params:
        actions:
          distribution: gaussian
          operation: additive
          range:
          - 0.0
          - 0.02
          range_correlated:
          - 0
          - 0.01
        actor_params:
          object:
            rigid_body_properties:
              mass:
                distribution: uniform
                operation: scaling
                range:
                - 0.7
                - 1.3
                setup_only: true
            rigid_shape_properties:
              friction:
                distribution: uniform
                num_buckets: 250
                operation: scaling
                range:
                - 0.7
                - 1.3
            scale:
              distribution: uniform
              operation: scaling
              range:
              - 0.97
              - 1.03
              setup_only: true
          robot:
            color: true
            dof_properties:
              lower:
                distribution: gaussian
                operation: additive
                range:
                - 0
                - 0.01
              upper:
                distribution: gaussian
                operation: additive
                range:
                - 0
                - 0.01
          table:
            rigid_shape_properties:
              friction:
                distribution: uniform
                num_buckets: 250
                operation: scaling
                range:
                - 0.5
                - 1.5
        frequency: 750
        observations:
          distribution: gaussian
          operation: additive
          range:
          - 0
          - 0.002
          range_correlated:
          - 0
          - 0.0
        sim_params:
          gravity:
            distribution: gaussian
            operation: additive
            range:
            - 0
            - 0.4
      randomize: true
task_name:
  desc: null
  value: Trifinger
test:
  desc: null
  value: false
torch_deterministic:
  desc: null
  value: false
train:
  desc: null
  value:
    asymmetric_obs: true
    params:
      algo:
        name: a2c_continuous
      config:
        bounds_loss_coef: 0.0001
        central_value_config:
          clip_value: true
          kl_threshold: 0.016
          learning_rate: 0.0005
          lr_schedule: linear
          mini_epochs: 4
          minibatch_size: 16384
          network:
            central_value: true
            mlp:
              activation: elu
              d2rl: false
              initializer:
                name: default
              regularizer:
                name: None
              units:
              - 512
              - 512
              - 256
              - 128
            name: actor_critic
          normalize_input: true
          schedule_type: standard
          truncate_grads: true
        clip_value: true
        critic_coef: 4
        e_clip: 0.2
        entropy_coef: 0.0
        env_name: rlgpu
        full_experiment_name: Trifinger
        gamma: 0.99
        grad_norm: 1.0
        horizon_length: 8
        kl_threshold: 0.016
        learning_rate: 0.0003
        lr_schedule: constant
        max_epochs: 20000
        mini_epochs: 4
        minibatch_size: 16384
        mixed_precision: false
        multi_gpu: false
        name: Trifinger
        normalize_advantage: true
        normalize_input: true
        normalize_value: true
        num_actors: 16384
        player:
          deterministic: true
          games_num: 1000000
          print_stats: false
        ppo: true
        print_stats: true
        reward_shaper:
          scale_value: 0.01
        save_best_after: 100
        save_frequency: 100
        schedule_type: standard
        score_to_win: 500000
        seq_len: 4
        tau: 0.95
        truncate_grads: true
        use_experimental_cv: true
      load_checkpoint: false
      load_path: ''
      model:
        name: continuous_a2c_logstd
      network:
        mlp:
          activation: elu
          d2rl: false
          initializer:
            name: default
          regularizer:
            name: None
          units:
          - 256
          - 256
          - 128
          - 128
        name: actor_critic
        separate: false
        space:
          continuous:
            fixed_sigma: true
            mu_activation: None
            mu_init:
              name: default
            sigma_activation: None
            sigma_init:
              name: const_initializer
              val: 0
      seed: 42
wandb_activate:
  desc: null
  value: true
wandb_entity:
  desc: null
  value: 2238046709-sjtu
wandb_group:
  desc: null
  value: Isaac_2024
wandb_logcode_dir:
  desc: null
  value: ''
wandb_name:
  desc: null
  value: Trifinger
wandb_project:
  desc: null
  value: isaacgymenvs
wandb_tags:
  desc: null
  value: []
