wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1735362026
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 13
      - 14
      - 35
      4: 3.7.12
      5: 0.12.21
      8:
      - 6
capture_video:
  desc: null
  value: false
capture_video_freq:
  desc: null
  value: 1464
capture_video_len:
  desc: null
  value: 100
checkpoint:
  desc: null
  value: ''
experiment:
  desc: null
  value: ''
force_render:
  desc: null
  value: true
graphics_device_id:
  desc: null
  value: 0
headless:
  desc: null
  value: false
max_iterations:
  desc: null
  value: ''
multi_gpu:
  desc: null
  value: false
num_envs:
  desc: null
  value: 4
num_subscenes:
  desc: null
  value: 4
num_threads:
  desc: null
  value: 4
pbt:
  desc: null
  value:
    enabled: false
physics_engine:
  desc: null
  value: physx
pipeline:
  desc: null
  value: gpu
rl_device:
  desc: null
  value: cuda:0
seed:
  desc: null
  value: 42
sigma:
  desc: null
  value: ''
sim_device:
  desc: null
  value: cuda:0
solver_type:
  desc: null
  value: 1
task:
  desc: null
  value:
    env:
      baseInitState:
        pos:
        - 0.0
        - 0.0
        - 0.62
        rot:
        - 0.0
        - 0.0
        - 0.0
        - 1.0
        vAngular:
        - 0.0
        - 0.0
        - 0.0
        vLinear:
        - 0.0
        - 0.0
        - 0.0
      clipActions: 1.0
      clipObservations: 5.0
      control:
        actionScale: 0.5
        controlFrequencyInv: 1
        damping: 2.0
        stiffness: 85.0
      defaultJointAngles:
        LF_HAA: 0.03
        LF_HFE: 0.4
        LF_KFE: -0.8
        LH_HAA: 0.03
        LH_HFE: -0.4
        LH_KFE: 0.8
        RF_HAA: -0.03
        RF_HFE: 0.4
        RF_KFE: -0.8
        RH_HAA: -0.03
        RH_HFE: -0.4
        RH_KFE: 0.8
      enableCameraSensors: false
      envSpacing: 4.0
      learn:
        angularVelocityScale: 0.25
        angularVelocityZRewardScale: 0.5
        dofPositionScale: 1.0
        dofVelocityScale: 0.05
        episodeLength_s: 50
        linearVelocityScale: 2.0
        linearVelocityXYRewardScale: 1.0
        torqueRewardScale: -2.5e-05
      numEnvs: 4
      plane:
        dynamicFriction: 1.0
        restitution: 0.0
        staticFriction: 1.0
      randomCommandVelocityRanges:
        linear_x:
        - -2.0
        - 2.0
        linear_y:
        - -1.0
        - 1.0
        yaw:
        - -1.0
        - 1.0
      urdfAsset:
        collapseFixedJoints: true
        defaultDofDriveMode: 4
        fixBaseLink: false
      viewer:
        lookat:
        - 1.0
        - 1
        - 3.3
        pos:
        - 0
        - 0
        - 4
        refEnv: 0
    name: Anymal
    physics_engine: physx
    sim:
      dt: 0.02
      gravity:
      - 0.0
      - 0.0
      - -9.81
      physx:
        bounce_threshold_velocity: 0.2
        contact_collection: 1
        contact_offset: 0.02
        default_buffer_size_multiplier: 5.0
        max_depenetration_velocity: 100.0
        max_gpu_contact_pairs: 8388608
        num_position_iterations: 4
        num_subscenes: 4
        num_threads: 4
        num_velocity_iterations: 1
        rest_offset: 0.0
        solver_type: 1
        use_gpu: true
      substeps: 2
      up_axis: z
      use_gpu_pipeline: true
    task:
      randomization_params:
        actions:
          distribution: gaussian
          operation: additive
          range:
          - 0.0
          - 0.02
        actor_params:
          anymal:
            color: true
            dof_properties:
              damping:
                distribution: uniform
                operation: scaling
                range:
                - 0.5
                - 1.5
                schedule: linear
                schedule_steps: 3000
              lower:
                distribution: gaussian
                operation: additive
                range:
                - 0
                - 0.01
                schedule: linear
                schedule_steps: 3000
              stiffness:
                distribution: uniform
                operation: scaling
                range:
                - 0.5
                - 1.5
                schedule: linear
                schedule_steps: 3000
              upper:
                distribution: gaussian
                operation: additive
                range:
                - 0
                - 0.01
                schedule: linear
                schedule_steps: 3000
            rigid_body_properties:
              mass:
                distribution: uniform
                operation: scaling
                range:
                - 0.5
                - 1.5
                schedule: linear
                schedule_steps: 3000
                setup_only: true
            rigid_shape_properties:
              friction:
                distribution: uniform
                num_buckets: 500
                operation: scaling
                range:
                - 0.7
                - 1.3
                schedule: linear
                schedule_steps: 3000
              restitution:
                distribution: uniform
                operation: scaling
                range:
                - 0.0
                - 0.7
                schedule: linear
                schedule_steps: 3000
        frequency: 600
        observations:
          distribution: gaussian
          operation: additive
          range:
          - 0
          - 0.002
        sim_params:
          gravity:
            distribution: gaussian
            operation: additive
            range:
            - 0
            - 0.4
            schedule: linear
            schedule_steps: 3000
      randomize: false
task_name:
  desc: null
  value: Anymal
test:
  desc: null
  value: false
torch_deterministic:
  desc: null
  value: false
train:
  desc: null
  value:
    params:
      algo:
        name: a2c_continuous
      config:
        bounds_loss_coef: 0.001
        clip_value: true
        critic_coef: 2
        e_clip: 0.2
        entropy_coef: 0.0
        env_name: rlgpu
        full_experiment_name: Anymal
        gamma: 0.99
        grad_norm: 1.0
        horizon_length: 24
        kl_threshold: 0.008
        learning_rate: 0.0003
        lr_schedule: adaptive
        max_epochs: 1000
        mini_epochs: 5
        minibatch_size: 32768
        mixed_precision: true
        multi_gpu: false
        name: Anymal
        normalize_advantage: true
        normalize_input: true
        normalize_value: true
        num_actors: 4
        ppo: true
        print_stats: true
        reward_shaper:
          scale_value: 1.0
        save_best_after: 200
        save_frequency: 50
        score_to_win: 20000
        seq_len: 4
        tau: 0.95
        truncate_grads: true
        value_bootstrap: true
      load_checkpoint: false
      load_path: ''
      model:
        name: continuous_a2c_logstd
      network:
        mlp:
          activation: elu
          d2rl: false
          initializer:
            name: default
          regularizer:
            name: None
          units:
          - 256
          - 128
          - 64
        name: actor_critic
        separate: false
        space:
          continuous:
            fixed_sigma: true
            mu_activation: None
            mu_init:
              name: default
            sigma_activation: None
            sigma_init:
              name: const_initializer
              val: 0.0
      seed: 42
wandb_activate:
  desc: null
  value: true
wandb_entity:
  desc: null
  value: 2238046709-sjtu
wandb_group:
  desc: null
  value: Isaac_2024
wandb_logcode_dir:
  desc: null
  value: ''
wandb_name:
  desc: null
  value: Anymal
wandb_project:
  desc: null
  value: isaacgymenvs
wandb_tags:
  desc: null
  value: []
