wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1735362490
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 13
      - 14
      - 35
      4: 3.7.12
      5: 0.12.21
      8:
      - 6
capture_video:
  desc: null
  value: false
capture_video_freq:
  desc: null
  value: 1464
capture_video_len:
  desc: null
  value: 100
checkpoint:
  desc: null
  value: ''
experiment:
  desc: null
  value: ''
force_render:
  desc: null
  value: true
graphics_device_id:
  desc: null
  value: 0
headless:
  desc: null
  value: false
max_iterations:
  desc: null
  value: ''
multi_gpu:
  desc: null
  value: false
num_envs:
  desc: null
  value: ''
num_subscenes:
  desc: null
  value: 4
num_threads:
  desc: null
  value: 4
pbt:
  desc: null
  value:
    enabled: false
physics_engine:
  desc: null
  value: physx
pipeline:
  desc: null
  value: gpu
rl_device:
  desc: null
  value: cuda:0
seed:
  desc: null
  value: 42
sigma:
  desc: null
  value: ''
sim_device:
  desc: null
  value: cuda:0
solver_type:
  desc: null
  value: 1
task:
  desc: null
  value:
    ctrl:
      all:
        gripper_deriv_gains:
        - 2
        - 2
        gripper_prop_gains:
        - 50
        - 50
        jacobian_type: geometric
      closed_loop_force:
        force_ctrl_axes:
        - 0
        - 0
        - 1
        - 0
        - 0
        - 0
        wrench_prop_gains:
        - 0.1
        - 0.1
        - 0.1
        - 0.1
        - 0.1
        - 0.1
      ctrl_type: joint_space_id
      gym_default:
        gripper_deriv_gains:
        - 20
        - 20
        gripper_prop_gains:
        - 500
        - 500
        ik_method: dls
        joint_deriv_gains:
        - 8
        - 8
        - 8
        - 8
        - 8
        - 8
        - 8
        joint_prop_gains:
        - 40
        - 40
        - 40
        - 40
        - 40
        - 40
        - 40
      hybrid_force_motion:
        force_ctrl_axes:
        - 0
        - 0
        - 1
        - 0
        - 0
        - 0
        motion_ctrl_axes:
        - 1
        - 1
        - 0
        - 1
        - 1
        - 1
        task_deriv_gains:
        - 8
        - 8
        - 8
        - 8
        - 8
        - 8
        task_prop_gains:
        - 40
        - 40
        - 40
        - 40
        - 40
        - 40
        wrench_prop_gains:
        - 0.1
        - 0.1
        - 0.1
        - 0.1
        - 0.1
        - 0.1
      joint_space_id:
        ik_method: dls
        joint_deriv_gains:
        - 8
        - 8
        - 8
        - 8
        - 8
        - 8
        - 8
        joint_prop_gains:
        - 40
        - 40
        - 40
        - 40
        - 40
        - 40
        - 40
      joint_space_ik:
        ik_method: dls
        joint_deriv_gains:
        - 0.1
        - 0.1
        - 0.1
        - 0.1
        - 0.1
        - 0.1
        - 0.1
        joint_prop_gains:
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
      open_loop_force:
        force_ctrl_axes:
        - 0
        - 0
        - 1
        - 0
        - 0
        - 0
      operational_space_motion:
        motion_ctrl_axes:
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        task_deriv_gains:
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        task_prop_gains:
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
      task_space_impedance:
        motion_ctrl_axes:
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        task_deriv_gains:
        - 8
        - 8
        - 8
        - 8
        - 8
        - 8
        task_prop_gains:
        - 40
        - 40
        - 40
        - 40
        - 40
        - 40
    env:
      close_and_lift: true
      env_spacing: 0.5
      franka_depth: 0.5
      franka_friction: 1.0
      numActions: 12
      numEnvs: 128
      numObservations: 20
      num_gripper_close_sim_steps: 25
      num_gripper_lift_sim_steps: 25
      num_gripper_move_sim_steps: 20
      table_friction: 0.3
      table_height: 0.4
    mode:
      export_scene: false
      export_states: false
    name: FactoryTaskNutBoltPick
    physics_engine: physx
    randomize:
      bolt_pos_xy_initial:
      - 0.0
      - 0.0
      bolt_pos_xy_noise:
      - 0.1
      - 0.1
      fingertip_midpoint_pos_initial:
      - 0.0
      - -0.2
      - 0.2
      fingertip_midpoint_pos_noise:
      - 0.2
      - 0.2
      - 0.1
      fingertip_midpoint_rot_initial:
      - 3.1416
      - 0
      - 3.1416
      fingertip_midpoint_rot_noise:
      - 0.3
      - 0.3
      - 1
      franka_arm_initial_dof_pos:
      - 0.3413
      - -0.8011
      - -0.067
      - -1.8299
      - 0.0266
      - 1.0185
      - 1.0927
      nut_pos_xy_initial:
      - 0.0
      - -0.3
      nut_pos_xy_initial_noise:
      - 0.1
      - 0.1
    rl:
      action_penalty_scale: 0.0
      clamp_rot: true
      clamp_rot_thresh: 1.0e-06
      force_action_scale:
      - 1.0
      - 1.0
      - 1.0
      keypoint_reward_scale: 1.0
      keypoint_scale: 0.5
      max_episode_length: 100
      num_keypoints: 4
      pos_action_scale:
      - 0.1
      - 0.1
      - 0.1
      rot_action_scale:
      - 0.1
      - 0.1
      - 0.1
      success_bonus: 0.0
      torque_action_scale:
      - 1.0
      - 1.0
      - 1.0
    sim:
      add_damping: true
      disable_gravity: false
      dt: 0.016667
      gravity:
      - 0.0
      - 0.0
      - -9.81
      physx:
        bounce_threshold_velocity: 0.2
        contact_collection: 1
        contact_offset: 0.005
        default_buffer_size_multiplier: 8.0
        friction_correlation_distance: 0.00625
        friction_offset_threshold: 0.01
        max_depenetration_velocity: 5.0
        max_gpu_contact_pairs: 1048576
        num_position_iterations: 16
        num_subscenes: 4
        num_threads: 4
        num_velocity_iterations: 0
        rest_offset: 0.0
        solver_type: 1
        use_gpu: true
      substeps: 2
      up_axis: z
      use_gpu_pipeline: true
task_name:
  desc: null
  value: FactoryTaskNutBoltPick
test:
  desc: null
  value: false
torch_deterministic:
  desc: null
  value: false
train:
  desc: null
  value:
    params:
      algo:
        name: a2c_continuous
      config:
        bounds_loss_coef: 0.0001
        clip_value: true
        critic_coef: 2
        e_clip: 0.2
        entropy_coef: 0.0
        env_name: rlgpu
        full_experiment_name: FactoryTaskNutBoltPick
        gamma: 0.99
        grad_norm: 1.0
        horizon_length: 120
        kl_threshold: 0.016
        learning_rate: 0.0001
        lr_schedule: fixed
        max_epochs: 1024
        mini_epochs: 8
        minibatch_size: 512
        mixed_precision: true
        multi_gpu: false
        name: FactoryTaskNutBoltPick
        normalize_advantage: true
        normalize_input: true
        normalize_value: true
        num_actors: 128
        ppo: true
        print_stats: true
        reward_shaper:
          scale_value: 1.0
        save_best_after: 50
        save_frequency: 100
        schedule_type: standard
        score_to_win: 20000
        seq_len: 4
        tau: 0.95
        truncate_grads: false
        value_bootstrap: true
      load_checkpoint: false
      load_path: ''
      model:
        name: continuous_a2c_logstd
      network:
        mlp:
          activation: elu
          d2rl: false
          initializer:
            name: default
          regularizer:
            name: None
          units:
          - 256
          - 128
          - 64
        name: actor_critic
        separate: false
        space:
          continuous:
            fixed_sigma: true
            mu_activation: None
            mu_init:
              name: default
            sigma_activation: None
            sigma_init:
              name: const_initializer
              val: 0
      seed: 42
wandb_activate:
  desc: null
  value: true
wandb_entity:
  desc: null
  value: 2238046709-sjtu
wandb_group:
  desc: null
  value: Isaac_2024
wandb_logcode_dir:
  desc: null
  value: ''
wandb_name:
  desc: null
  value: FactoryTaskNutBoltPick
wandb_project:
  desc: null
  value: isaacgymenvs
wandb_tags:
  desc: null
  value: []
